services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: trombinoscope_api
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - trombinoscope-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trombinoscope_app
    depends_on:
      - db
    ports:
      - "9081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/trombinoscope_api
    networks:
      - trombinoscope-net
    volumes:
      - app-data:/application/uploads

volumes:
  db-data:
  app-data:

networks:
  trombinoscope-net:
